name: Repository Consistency Check

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  check-consistency:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check repository structure
      run: |
        echo "Checking repository structure..."
        
        # Verify required directories exist
        if [ -d "opencode" ]; then
          echo "✓ opencode directory found"
        else
          echo "✗ opencode directory missing"
          exit 1
        fi
        
        # Check for opencode.json
        if [ -f "opencode.json" ]; then
          echo "✓ opencode.json found"
        else
          echo "✗ opencode.json missing"
          exit 1
        fi
        
        # Verify opencode subdirectories
        if [ -d "opencode/.prompts" ] && [ -d "opencode/.rules" ]; then
          echo "✓ Required subdirectories found"
        else
          echo "✗ Missing required subdirectories (.prompts or .rules)"
          exit 1
        fi
        
        echo "Repository structure is consistent ✓"

    - name: Validate JSON format
      run: |
        echo "Validating opencode.json format..."
        if python3 -m json.tool opencode.json > /dev/null 2>&1; then
          echo "✓ JSON is valid"
        else
          echo "✗ JSON format is invalid"
          exit 1
        fi